
name: test-action

on:
  workflow_dispatch:
    inputs:
      skip_check_run:
        required: false
      gist_name:
        required: false
      set_check_status_from_test_outcome:
        required: false
  #push:
  #release:
  #  types: published

jobs:

  run-tests:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
    runs-on: ${{ matrix.os }}
    steps:

      - name: checkout
        uses: actions/checkout@v1
      
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-preview.7.20366.6'

      - name: use this action, default args (missing solution/project paths)
        ## We expect this one to fail
        continue-on-error: true
        id: testAction1
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      ## This one does not work as expected because
      ## VSTest logs all projects in a solution to
      ## the same output file, overwriting the TRX
      ## each time, so only the last one wins!
      ##   https://github.com/microsoft/vstest/issues/2113
      ##   https://github.com/microsoft/vstest/issues/880
      - name: use this action, test solution dir
        if: ${{ !cancelled() }}
        id: testAction2
        uses: ./
        with:
          project_path: tests
          report_name: tests_0_all_in_solution-${{ matrix.os }}
          report_title: All Tests In Solution -- Last Project Wins!
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: use this action, xunit project dir
        if: ${{ !cancelled() }}
        id: testAction3a
        uses: ./
        with:
          project_path: tests/samples.xunit/AssertExamples
          report_name: tests_1_xunit-${{ matrix.os }}
          report_title: Sample XUnit Tests (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit-${{ matrix.os }}.md
          gist_badge_label: 'XUnit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: use this action, xunit project dir no restore no build
        if: ${{ !cancelled() }}
        id: testAction3a1
        uses: ./
        with:
          project_path: tests/samples.xunit/AssertExamples
          report_name: tests_1_xunit-norestore-nobuild-${{ matrix.os }}
          report_title: Sample XUnit Tests without build or restore (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_restore: true
          no_build: true

      - name: use this action, xunit project dir, ALTERNATE XSL
        if: ${{ !cancelled() }}
        id: testAction3a2
        uses: ./
        with:
          project_path: tests/samples.xunit/AssertExamples
          report_name: tests_1_xunit_altxsl-${{ matrix.os }}
          report_title: Sample XUnit Tests (Alt XSL) (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit_altxsl-${{ matrix.os }}.md
          gist_badge_label: 'XUnit Tests (Alt XSL): %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
          trx_xsl_path: trx-report/trx2md-alt-sample.xsl

      - name: use this action, nunit project dir
        if: ${{ !cancelled() }}  
        id: testAction3b
        uses: ./
        with:
          project_path: tests/nunit-csharp-samples/syntax
          report_name: tests_2_nunit-${{ matrix.os }}
          report_title: Sample NUnit Tests (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_nunit-${{ matrix.os }}.md
          gist_badge_label: 'NUnit Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}

      - name: use this action, mstest project dir
        if: ${{ !cancelled() }}  
        id: testAction3c
        uses: ./
        with:
          project_path: tests/rafaelfgx_DotNetTests/MSTest
          report_name: tests_3_mstest-${{ matrix.os }}
          report_title: Sample MSTest Tests (${{ matrix.os }})
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_mstest-${{ matrix.os }}.md
          gist_badge_label: 'MSTest Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
      
      - name: dump test results
        shell: pwsh
        run: |
          Write-ActionInfo 'Testing on: ${{ matrix.os }}'
          Write-ActionInfo '  xUnit:'
          Write-ActionInfo '    * result_value    = ${{ steps.testAction3a.outputs.result_value }}'
          Write-ActionInfo '    * total_count     = ${{ steps.testAction3a.outputs.total_count }}'
          Write-ActionInfo '    * passed_count    = ${{ steps.testAction3a.outputs.passed_count }}'
          Write-ActionInfo '    * failed_count    = ${{ steps.testAction3a.outputs.failed_count }}'
          Write-ActionInfo '    * gist_report_url = ${{ steps.testAction3a.outputs.gist_report_url }}'
          Write-ActionInfo '    * gist_badge_url  = ${{ steps.testAction3a.outputs.gist_badge_url }}'
          Write-ActionInfo ''
          Write-ActionInfo '  xUnit (XSL Alt):'
          Write-ActionInfo '    * result_value    = ${{ steps.testAction3a2.outputs.result_value }}'
          Write-ActionInfo '    * total_count     = ${{ steps.testAction3a2.outputs.total_count }}'
          Write-ActionInfo '    * passed_count    = ${{ steps.testAction3a2.outputs.passed_count }}'
          Write-ActionInfo '    * failed_count    = ${{ steps.testAction3a2.outputs.failed_count }}'
          Write-ActionInfo '    * gist_report_url = ${{ steps.testAction3a2.outputs.gist_report_url }}'
          Write-ActionInfo '    * gist_badge_url  = ${{ steps.testAction3a2.outputs.gist_badge_url }}'
          Write-ActionInfo ''
          Write-ActionInfo '  NUnit:'
          Write-ActionInfo '    * result_value    = ${{ steps.testAction3b.outputs.result_value }}'
          Write-ActionInfo '    * total_count     = ${{ steps.testAction3b.outputs.total_count }}'
          Write-ActionInfo '    * passed_count    = ${{ steps.testAction3b.outputs.passed_count }}'
          Write-ActionInfo '    * failed_count    = ${{ steps.testAction3b.outputs.failed_count }}'
          Write-ActionInfo '    * gist_report_url = ${{ steps.testAction3b.outputs.gist_report_url }}'
          Write-ActionInfo '    * gist_badge_url  = ${{ steps.testAction3b.outputs.gist_badge_url }}'
          Write-ActionInfo ''
          Write-ActionInfo '  MSTest:'
          Write-ActionInfo '    * result_value    = ${{ steps.testAction3c.outputs.result_value }}'
          Write-ActionInfo '    * total_count     = ${{ steps.testAction3c.outputs.total_count }}'
          Write-ActionInfo '    * passed_count    = ${{ steps.testAction3c.outputs.passed_count }}'
          Write-ActionInfo '    * failed_count    = ${{ steps.testAction3c.outputs.failed_count }}'
          Write-ActionInfo '    * gist_report_url = ${{ steps.testAction3c.outputs.gist_report_url }}'
          Write-ActionInfo '    * gist_badge_url  = ${{ steps.testAction3c.outputs.gist_badge_url }}'
          Write-ActionInfo ''
